### ISSUE TITLE
升级了openssl到1.1.1d但是还是报错

### ISSUE THREAD

**Issue by feixiangdao** [shmilylty/OneForAll#47]
**是否使用了最新代码**
是
**Bug描述**
运行oneforall报错：
RuntimeError: Sorry but the OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare.
但是已经升级到openssl 1.1.1d了：
[root@vultr oneforall]# openssl version 
OpenSSL 1.1.1d  10 Sep 2019

**如何复现**
复现步骤（可不写）
复现命令

**预期结果**
清晰而简洁的预期结果描述（可不写）

**实际结果**
清晰而简洁的实际结果描述（如出现什么错误）

**屏幕截图**

**运行环境**
 - 系统：centos
 - Python版本：3.8.1
- OneForAll版本：[例如0.0.6]

**报错文本**
复制完整的报错文本

**Comment by shmilylty** [comment]
参考#40

**Comment by depycode** [comment]
也是同样的问题，csdn的方案无法解决。
`[root@vultr oneforall]# python3 oneforall.py --target ./domains.txt --brute True run

OneForAll是一款功能强大的子域收集工具
             ___             _ _ 
 ___ ___ ___|  _|___ ___ ___| | | {v0.0.8#dev}
| . |   | -_|  _| . |  _| .'| | | 
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll处于开发中，会进行版本快速迭代，请每次在使用前进行更新！

[*] Starting OneForAll @ 2020-02-15 05:08:07

05:08:07,585 [INFOR] oneforall:195 - 开始运行OneForAll
05:08:07,590 [INFOR] utils:131 - 获取到2个域名
05:08:07,591 [INFOR] collect:55 - 开始收集example.com的子域
RuntimeError: Sorry but the OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare.
[root@vultr oneforall]# openssl version
OpenSSL 1.1.1-pre8 (beta) 20 Jun 2018`
`[root@vultr Python-3.9.0a1]# ./configure --prefix=/usr/local/python3.9 --with-openssl=/usr/local/openssl`
`[root@vultr Python-3.9.0a1]# python3 -V
Python 3.9.0a1
[root@vultr Python-3.9.0a1]# `

**Comment by shmilylty** [comment]
yum install openssl-devel
yum install pyOpenSSL

**Comment by feixiangdao** [comment]
还是不行，问题一样，我是用pyenv安装python 3.8的，不知道跟这个有没有关系

**Comment by shmilylty** [comment]
![image](https://user-images.githubusercontent.com/24275308/74904245-67f64e00-53e6-11ea-8c16-3dd6cac5bafb.png)
这个问题的根本原因是你的python的openssl库版本过低，不是openssl版本过低。

**Comment by feixiangdao** [comment]
请教下python的openssl库版本过低的问题怎么解决，搜索了很多还是解决不了

**Comment by shmilylty** [comment]
现在最新的OneForAll不使用到openssl，关闭此问题。
